# https://yazi-rs.github.io/docs/next/configuration/yazi#mgr
[mgr]
linemode = "size_and_mtime"
mouse_events = ["click", "scroll", "touch", "move", "drag"]
ratio = [1, 4, 3]
scrolloff = 100
show_hidden = false
show_symlink = false
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true
sort_translit = true
title_format = "{cwd}"

# https://yazi-rs.github.io/docs/next/configuration/yazi#preview
[preview]
wrap = "yes"
tab_size = 2
max_width = 2560
max_height = 5120
image_filter = "triangle"
image_quality = 70
uberzug_scale = 1.5

# https://yazi-rs.github.io/docs/next/configuration/yazi#opener
# [opener]
# play = [
#   { run = "mpv %s", orphan = true, for = "linux" },
# ]
# edit = 
